apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: mindx-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mindx-api
  template:
    metadata:
      labels:
        app: mindx-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: api-container
        image: mindxtunght104.azurecr.io/mindx-onboarding-backend:latest
        ports:
        - containerPort: 3000 # Cổng API chạy bên trong container
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secrets   
              key: JWT_SECRET      
        - name: NODE_ENV
          value: "production"
        # Thiết lập health check
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10