apiVersion: v1
kind: Service
metadata:
  name: api-service # Tên này sẽ dùng để Frontend gọi API nội bộ
spec:
  selector:
    app: mindx-api # Phải khớp với label trong Deployment ở trên
  ports:
    - protocol: TCP
      port: 3000       # Cổng mà Service tiếp nhận
      targetPort: 3000 # Cổng thực tế của Pod
  type: ClusterIP # Chỉ cho phép truy cập nội bộ trong Cluster